# Generated by Django 3.0.8 on 2020-07-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soundtrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('songfile', models.FileField(upload_to='media/musics/', verbose_name='Трек')),
                ('image', models.ImageField(upload_to='static/images/logo', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
    ]
