# Generated by Django 3.0.8 on 2020-07-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200717_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundtrack',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/logo', verbose_name='Логотип'),
        ),
    ]
